# Gradle build properties
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official

kotlinVersion=2.0.21
coroutinesVersion=1.8.1
ktorVersion=2.3.12
logbackVersion=1.5.8
slf4jVersion=2.0.16
cliktVersion=4.4.0
bouncyCastleVersion=1.78.1
junitVersion=5.11.3
kotestVersion=5.9.1
sqliteVersion=3.47.1.0
jacksonVersion=2.18.2
